# Traefik Configuration for Kamal Singh Portfolio
# Binary Traefik setup with custom ports and existing SSL certificate

[api]
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":81"
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"
          permanent = true

  [entryPoints.websecure]
    address = ":434"

[providers]
  [providers.file]
    filename = "/path/to/your/traefik/dynamic.toml"
    watch = true

# No certificatesResolvers needed - using existing IONOS wildcard certificate
# SSL certificate should be configured in your existing Traefik setup

# Optional: Metrics for monitoring
[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addServicesLabels = true

# Logging
[log]
  level = "INFO"
  filePath = "/var/log/traefik/traefik.log"

[accessLog]
  filePath = "/var/log/traefik/access.log"